# Generated by Django 5.1.7 on 2026-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localcosmos_server', '0007_localcosmosuser_legacy_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverexternalmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('mp3', 'MP3 File'), ('wav', 'WAV File'), ('pdf', 'PDF Document'), ('website', 'Website'), ('file', 'File')], max_length=50),
        ),
    ]
