# Generated by Django 5.1.7 on 2026-07-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localcosmos_server', '0008_alter_serverexternalmedia_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servercontentimage',
            options={'ordering': ['position', 'pk']},
        ),
    ]
