# Generated by Django 4.1.5 on 2023-02-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localcosmos_server', '0003_alter_localcosmosuser_follows'),
        ('template_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('navigation_type', models.CharField(max_length=355)),
                ('options', models.JSONField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localcosmos_server.app')),
            ],
            options={
                'unique_together': {('app', 'navigation_type')},
            },
        ),
        migrations.RemoveField(
            model_name='localizedtemplatecontent',
            name='draft_navigation_link_name',
        ),
        migrations.RemoveField(
            model_name='localizedtemplatecontent',
            name='published_navigation_link_name',
        ),
        migrations.CreateModel(
            name='NavigationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=355)),
                ('url', models.CharField(max_length=355, null=True)),
                ('options', models.JSONField(null=True)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_content.navigation')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_content.navigationentry')),
                ('template_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_content.templatecontent')),
            ],
        ),
    ]
