# Generated by Django 4.1.5 on 2023-02-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_content', '0002_navigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationentry',
            name='link_name',
        ),
        migrations.CreateModel(
            name='LocalizedNavigationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15)),
                ('link_name', models.CharField(max_length=355)),
                ('navigation_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_content.navigationentry')),
            ],
            options={
                'unique_together': {('navigation_entry', 'language')},
            },
        ),
    ]
