# Generated by Django 4.1.5 on 2023-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_content', '0003_remove_navigationentry_link_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationentry',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.RemoveField(
            model_name='templatecontent',
            name='tag',
        ),
        migrations.AddField(
            model_name='navigationentry',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='assignment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='template_type',
            field=models.CharField(choices=[('page', 'Page'), ('feature', 'Feature')], max_length=20),
        ),
    ]
