# Generated by Django 5.1.7 on 2026-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_content', '0004_localizedtemplatecontent_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecontent',
            name='published_template',
        ),
    ]
