# Generated by Django 5.1.7 on 2026-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_content', '0005_remove_templatecontent_published_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontent',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
