# Generated by Django 5.1.7 on 2026-07-18 06:31

import localcosmos_server.template_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_content', '0006_templatecontent_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizedtemplatecontent',
            options={'ordering': ['template_content__position', 'pk']},
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='published_template_definition',
            field=models.FileField(max_length=500, null=True, upload_to=localcosmos_server.template_content.models.get_published_page_template_definition_path),
        ),
    ]
