# Generated by Django 5.1.7 on 2026-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrulecondition',
            name='factor_type',
            field=models.CharField(choices=[('dataset', 'Dataset'), ('geography', 'Inside Geography'), ('taxon', 'Taxon'), ('is_first_dataset_for_user', 'Is first dataset for user'), ('is_first_species_in_polygon_for_user', 'Is first species in any polygon'), ('dataset_created', 'Dataset created')], max_length=100),
        ),
    ]
