# Generated by Django 6.1 on 2026-09-06 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localcosmos_server', '0009_alter_servercontentimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FCM_DJANGO_FCMDEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(blank=True, max_length=1024)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, default='', max_length=15)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localcosmos_server.app')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushReceivingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=15)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localcosmos_server.app')),
                ('fcm_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_receiving_device', to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
            ],
            options={
                'unique_together': {('app', 'client_id')},
            },
        ),
    ]
