# Generated by Django 5.1.7 on 2026-06-18 06:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localcosmos_server', '0008_alter_serverexternalmedia_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_categories', to='localcosmos_server.app')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_polygons', to='localcosmos_server.app')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_polygons', to='geography.polygoncategory')),
            ],
        ),
    ]
